//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingServer.RequestProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequestProxy.IRequestProxy")]
    public interface IRequestProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestProxy/JCDecauxRequest", ReplyAction="http://tempuri.org/IRequestProxy/JCDecauxRequestResponse")]
        string JCDecauxRequest(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestProxy/JCDecauxRequest", ReplyAction="http://tempuri.org/IRequestProxy/JCDecauxRequestResponse")]
        System.Threading.Tasks.Task<string> JCDecauxRequestAsync(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestProxyChannel : RoutingServer.RequestProxy.IRequestProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestProxyClient : System.ServiceModel.ClientBase<RoutingServer.RequestProxy.IRequestProxy>, RoutingServer.RequestProxy.IRequestProxy {
        
        public RequestProxyClient() {
        }
        
        public RequestProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string JCDecauxRequest(string city) {
            return base.Channel.JCDecauxRequest(city);
        }
        
        public System.Threading.Tasks.Task<string> JCDecauxRequestAsync(string city) {
            return base.Channel.JCDecauxRequestAsync(city);
        }
    }
}
